language: elm
elm:
  - elm0.19.0

script:
  - npm run build

deploy:
  provider: pages
  email: astarte-machine@ispirata.com
  name: Astarte Bot
  local_dir: dist/
  repo: astarte-platform/online-interface-builder
  fqdn: interfaces-editor.astarte-platform.org
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
