name: Code quality
on:
  push:
    branches:
      - master
      - 'release-*'
  create:
  pull_request:

jobs:
  build:
    name: Run code quality checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Check formatting
        run: npm run check-format
      - name: Check linting
        run: npm run check-lint
      - name: Check Typescript
        run: npm run check-types
      - name: Check App compilation
        run: npm run build
