name: Functionality tests
on:
  push:
    branches:
      - master
      - 'release-*'
  create:
  pull_request:

jobs:
  build:
    name: Run code quality and funcionality tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
          - 16
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ matrix.node_version }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Check formatting
        run: npm run check-format
      - name: Check linting
        run: npm run check-lint
      - name: Check Typescript
        run: npm run check-types
      - name: Start dev server
        run: npm run start-ci & npx wait-on http://localhost:8080
      - name: Run tests
        run: npm run test
